// Generated by CoffeeScript 1.4.0
var API, HOST, PAGE_COUNT, PATH, SYNC_INTERVAL, album2data, photo2data;

VERSION = '3.0'

PATH = '../api';

API = {
  USER: '/user.php',
  THUMB: '/thumb.php',
  LINE: '/list.php?t=photos',
  PHOTO: '/photo.php',
  PHOTO_LIST: '/list.php?t=albumPhotos',
  VIDEO: '/video.php',
  VIDEO_LIST: '/list.php?t=albumVideos',
  ALBUM: '/album.php',
  ALBUM_LIST: '/list.php?t=albums'
};

SYNC_INTERVAL = 1000;

PAGE_COUNT = 50;

photo2data = function(data) {
  return {
    id: $('id', data).text(),
    filename: $('cFileName', data).text(),
    title: $('cPictureTitle', data).text(),
    mime: $('mime', data).text(),
    size: $('iFileSize', data).text(),
    time: $('dateTime', data).text(),
    width: $('iWidth', data).text(),
    height: $('iHeight', data).text(),
    type: $('MediaType', data).text()
  };
};

album2data = function(data) {
  return {
    id: $('iPhotoAlbumId', data).text(),
    title: $('cAlbumTitle', data).text(),
    cover: $('iAlbumCover', data).text(),
    time: $('DateCreated', data).text()
  };
};

$.req = function(api, data, done, err) {
  return $.ajax(PATH + api, {
    type: 'post',
    dataType: 'xml',
    data: data,
    success: function(res) {
      //res = $.xml2json(res);
      var status = parseInt($('status',res).text(), 10);
      if (status === -99 || status === 98) {
        $('body').addClass('status-login');
      }
      if (status === 0 || status === 1) {
        return typeof done === "function" ? done(res,status) : void 0;
      } else {
        return typeof err === "function" ? err(status, $('error',res).text()) : void 0;
      }
    },
    error: function(jqXHR, textStatus, errorThrown) {
      return typeof err === "function" ? err(-404, 'offline') : void 0;
    }
  });
};

